### ISSUE TITLE
failure to find conditionalconformal.py

### ISSUE THREAD

**Issue by MisDrifter** [jjcherian/conformal-safety#1]
In the medical-qa.ipynb, it says 'from conditionalconformal import CondConf' in the fifth code block. But I couldn't find the respective 'conditionalconformal.py' in the folder and thus failed in running the code. How to solve the problem?

**Comment by jjcherian** [comment]
Ah whoops forgot to add conditionalconformal to requirements.txt but installing it from pip should fix that!

**Comment by MisDrifter** [comment]
【自动回复】亲，邮件收到了，灰常感谢！                                                   ——zlj
